---
dist: xenial
language: python
python: 3.7
# pre-commit hooks can use Docker, so we should go ahead and enable it
services: docker

env:
  global:
    - AWS_DEFAULT_REGION="us-east-1"
    # AWS_ACCESS_KEY_ID
    - secure: "BrBxhgo7iclbsCqyGusi2ZxVQSYRlOgDv33QKBpMnbSyDDpksADAt/F\
      mUxGodkWG4Sfjb2elWbAilwaRV4DpvdvKpyEWAqBRtTDKtB5OgGY5XHbbfofkZeD\
      JF5i8HhWyDWjMZPfm5q7s3/yZydw31UaYTw/YXtQsdJS8thOMZEuJ0ZPP4Z60faO\
      9fpTAvuL0A8KZ4y/MoVF6ggHAHoHEufIP3O+dIWWHh4pXxWJNQNcaumviBwKSbJi\
      0/qxgkDfOA5yHyqgMXbcBG/zpsz+6ABdp8et9eYNFMdldnvk8kexzFvabNaNfSIS\
      Sq1Yqx2SAbbazw/5XIa5/gFRweFuMWNNtw/PfZj51L41b69MCpdLARiSYQAKqUuz\
      MCXR2TzcGGkD/m4sEMRijC2fPvEFdAX5U1fMV/HHLpmHIKodjo9uK9SQImTFFCXJ\
      QDMoSRB2sjKESCKRd02sEzjFE5VfzxeQNX/yDh78DphbMh0HZ6DFi+mHgk+1ZJqz\
      M0/zKxVE3CqOR7ylUwJktJ9rcYhLqoQmzMsPTLVZ/D7Wf/o6GF8P9f4XnJnorDie\
      6k4b134YLe6qNrJ5zbWgcF9buId346Sat3wU1cUcm/Z4Pz1I/dMCa8WfpUGPjJOt\
      ugm2fw8zLOfSeDmyhg9ox5Hk9H6Ic/uB8kBk5LuOA0fD2gjcPp2Q="
    # AWS_SECRET_ACCESS_KEY
    - secure: "WpHq80toETepMY20ggKzbCs2D2LtB32QD1A+jqWvS5LaNF7mX73Tcm3\
      B60c1Yyu68cw3NX9VC+OVPbKuM+4d+PK8nhUV7cHSdRFhtYg5lKFmlMPTfYolNLp\
      2b83v5CApC4VeAbDQMQkOzg2eox1jDlWOGA8yoN3yLbhIjxkyw2kbVxsEToVs2je\
      aTshyG1rjkVxT0znRXIB8CTQgkUUdljNoWqg3M3DVEilrnDiISMD8Z29iuLixIqf\
      i5T1YkX/z8RSVqH18MgCjhsWWYs9vtf9t/yOqUimkfBgUk3nXPP8bTtYPV3+hk0J\
      PceEyKFIPMjyFVq+P8MH5DZFU6Bb4OC+EGr7ilaRFkSPebsinbK9xWFHVn/gw7D2\
      uh1KYp4kiiJ7Z83ImjEjjw+bF6nqEsw5+7htYENzNma4FksDsfQlDd515Sq//rcl\
      Fziqi3OhuKpc5lUGlFy3NIsJBNf2yMZuFL1SOLEnSMtKu/koDrgWY6JkVlsvn0PO\
      FyVSZCIy2b4LaB5LsGvsExL2jWqQ1XjMf2XVCqGsuR/de9CjLxViykWhtlYQLlX/\
      RXUm7wGA0JCLidNqywJKfS/M+trg4PasmabTugTZhGMo8ycBJ6ma0p0Lys6XiXUN\
      GxMOPwITMHkT82MP9brKfc3LsnKEA7gBmZuVeRJpjd2mBIC295iU="

# Install terraform and terraform-doc
before_install:
  - >
    wget
    https://releases.hashicorp.com/terraform/0.12.3/terraform_0.12.3_linux_amd64.zip
    -O terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
  - go get github.com/segmentio/terraform-docs

# Cache pip packages and pre-commit plugins to speed up builds
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

install:
  - pip install --upgrade -r requirements-test.txt

script:
  - pre-commit run --all-files
  - molecule test
