---
- name: Copy systemd service to run {{ item }}
  ansible.builtin.copy:
    dest: /etc/systemd/system/run-{{ item }}.service
    mode: u=rw,g=r,o=r
    src: run-{{ item }}.service
    # I'd like to validate the file here, but that can't be done
    # cleanly.  See ansible/ansible#19243.
    # validate: systemd-analyze verify %s

- name: Copy systemd timer to run {{ item }}
  ansible.builtin.template:
    dest: /etc/systemd/system/run-{{ item }}.timer
    mode: u=rw,g=r,o=r
    src: run-{{ item }}.j2.timer
    # I'd like to validate the file here, but that can't be done
    # cleanly.  See ansible/ansible#19243.
    # validate: systemd-analyze verify %s

- name: Enable the systemd timer
  ansible.builtin.systemd_service:
    daemon_reload: true
    enabled: true
    name: run-{{ item }}.timer
